### ISSUE TITLE
split microendpoint checks in separate repositories

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/microendpoint#11]
If we keep all checks inside microendpoint we will end up with microendpoint as a big dependency aggregator.

Right now we have K8s and vault. AWS is coming. Then maybe etcd and other stuff. K8s is ok - it's used in (almost) all our services, but other are not.

microendpoint is meant to be used by all of our services, so there is a glide/dep battles potential.

**Comment by xh3b4sd** [comment]
Then lets just have one repo for one endpoint.

**Comment by xh3b4sd** [comment]
Done.
